"""
389. Find the Difference
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.
Example:
Input:
s = "abcd"
t = "abcde"
Output:
e
Explanation:
'e' is the letter that was added.
"""
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        dic_s = Counter(s)
        dic_t = Counter(t)
        for k, v in dic_t.items():
            if k not in dic_s or v > dic_s[k]:
                return k